export const APP_COPY = {
  app: {
    name: "Cadence",
  },
  desktopOnly: {
    title: "请使用 Cadence 桌面版",
    body: "Cadence 的任务、设置和模型配置需要在 Tauri 桌面应用中运行。",
  },
  capture: {
    tabs: {
      future: "未来",
      history: "历史",
      weekly: "周总结",
    },
    placeholder: {
      default: "写下任务，例如：明天下午 3 点交方案 #工作 !高",
      clipboardImage: "已读取剪贴板图片，点击“识别”发送给模型",
      clipboardText: (content: string) =>
        `剪贴板：${content.replace(/\s+/g, " ").trim().slice(0, 96)}${content.length > 96 ? "…" : ""}`,
    },
    toast: {
      recognitionFailed: (message: string) => `识别失败：${message}`,
      clipboardImageReady: "已读取剪贴板图片，点击“识别”发送给模型",
      clipboardTextReady: "已读取剪贴板内容，点击“识别”发送给模型",
      taskCompleted: "任务已完成",
      taskReopened: "任务已重新打开",
      taskDeleted: "任务已删除",
      weeklyGenerated: "周总结已生成",
    },
    actions: {
      quickAdd: "快速添加任务",
      addTask: "添加任务",
      processing: "正在处理",
      confirmClipboardRecognition: "确认识别剪贴板内容",
      recognize: "识别",
      readClipboard: "读取剪贴板内容",
      captureScreen: "框选屏幕区域识别",
      expandPanel: "展开任务面板",
      collapsePanel: "收起任务面板",
    },
    errors: {
      emptyClipboard: "剪贴板里没有可识别的内容",
    },
    panel: {
      label: "任务面板",
      tabsLabel: "任务分类",
      historyTitle: "已完成",
      historyEmptyTitle: "还没有完成记录",
      historyEmptyText: "完成的任务会留在这里，方便回顾。",
      futureEmptyTitle: "接下来很清爽",
      futureEmptyText: "用上方输入框记下一件事，回车即可保存。",
      overdue: "逾期",
      today: "今天",
      later: "以后",
      unscheduled: "待安排",
    },
    weekly: {
      intro: "回顾完成过的事，也为下一周留出空间。",
      generateData: "生成数据版",
      generateAi: "AI 总结",
      emptyList: "还没有周总结。",
      aiReport: "AI 版",
      dataReport: "数据版",
      emptyTitle: "生成第一份周总结",
      emptyText: "Cadence 会根据本地任务历史整理完成情况与下周重点。",
    },
  },
  settings: {
    heading: "设置",
    tabListLabel: "设置分类",
    tabs: {
      basic: {
        label: "基础偏好",
        description: "主题、默认时间、周总结",
      },
      ai: {
        label: "AI 服务",
        description: "服务地址、密钥、模型",
      },
      lark: {
        label: "飞书同步",
        description: "应用授权、同步目标",
      },
    },
    fields: {
      defaultDueHour: { label: "默认截止小时" },
      theme: { label: "主题" },
      weeklyEnabled: { label: "自动生成周总结" },
      weeklyDay: { label: "生成星期" },
      weeklyTime: { label: "生成时间" },
      aiBaseUrl: { label: "服务地址", placeholder: "https://.../v1" },
      aiKey: { label: "API Key", placeholder: "留空不修改" },
      aiTextModel: { label: "文本模型", placeholder: "输入模型名称" },
      aiVisionModel: { label: "视觉模型", placeholder: "输入模型名称" },
      larkAppId: { label: "App ID" },
      larkSecret: { label: "App Secret", placeholder: "留空不修改" },
      larkBaseUrl: { label: "多维表格链接", placeholder: "https://.../base/...?...table=..." },
      larkDocumentUrl: { label: "周总结文档链接" },
    },
    options: {
      theme: {
        system: "跟随系统",
        light: "浅色",
        dark: "深色",
      },
      weekdays: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
    },
    toast: {
      saved: "设置已保存",
      larkConnected: "飞书已连接",
    },
    actions: {
      save: "保存设置",
      waitingAuth: "等待授权",
      saveAndConnectLark: "保存并连接飞书",
    },
  },
  taskItem: {
    completeTask: (title: string) => `完成 ${title}`,
    reopenTaskWithTitle: (title: string) => `重新打开 ${title}`,
    reopen: "重新打开",
    delete: "删除任务",
    overduePrefix: "已逾期 · ",
    highPriority: "高优先级",
  },
  draftReview: {
    eyebrow: "智能识别",
    title: "确认要创建的任务",
    body: "Cadence 不会在你确认前写入任务。",
    close: "关闭",
    needsConfirmation: "需要确认",
    selectedCount: (selected: number, total: number) => `已选择 ${selected} / ${total}`,
    cancel: "取消",
    saving: "正在创建…",
    createTasks: (count: number) => `创建 ${count} 项任务`,
  },
  screenshotSelection: {
    windowLabel: "框选屏幕识别区域",
    hint: "拖动框选要识别的区域",
    cancelWithEsc: "按 Esc 取消",
    selectedSize: (width: number, height: number) => `已选择 ${Math.round(width)} × ${Math.round(height)}`,
    actions: {
      cancel: "取消",
      submitted: "已提交…",
      recognizeSelection: "识别选区",
    },
  },
  screenshotCropper: {
    dialogLabel: "框选屏幕内容",
    title: "框选要识别的区域",
    body: "拖动鼠标选择；不框选则识别整个屏幕。",
    close: "关闭截图",
    imageAlt: "待识别的屏幕截图",
    cancel: "取消",
    recognizing: "正在识别…",
    recognizeSelection: "识别选中区域",
  },
  due: {
    unscheduled: "未安排",
    todayPrefix: "今天",
  },
} as const;
